ingress:
  enabled: true
  hosts:
    - host: ayamjutgray.prueba.pe
      paths:
        - path: /
          pathType: Prefix
  tls: []
# Desactivaci√≥n de Sentry y NFS
# sentry:
#   enabled: false
# nfs:
#   enabled: false
# Prueba de actualizacion MAVG.
# Segunda prueba actualizacion.